### ISSUE TITLE
sa-learn: "Permission denied". Running user has no permissions on the current working directory

### ISSUE THREAD

**Issue by jobhh** [poralix/directadmin-teach-sa#3] opened 2017-10-09 17:12 UTC
Something seem to be broken with permissions... Do you per chance know how to fix this? Otherwise I'll Google it at a later stage and report back.

    [Mon Oct  9 18:21:01 CEST 2017] [OK] Started!
    [Mon Oct  9 18:21:01 CEST 2017] [INFO] Running /usr/local/directadmin/scripts/custom/directadmin-teach-sa/cron_sa_learn.sh as user root
    [Mon Oct  9 18:21:01 CEST 2017] [OK] The binary sudo was found
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [admin] Running for user admin
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [admin] [+] found system mail account in /home/admin/Maildir
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [admin] [-] Nothing to synchronize yet
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [admin] Finished with user admin
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] Running for user *user1*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] [+] found system mail account in /home/*user1*/Maildir
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] [+] found domain *domain1* owned by *user1*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] [+] found domain *domain2* owned by *user1*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] [+] found domain *domain3* owned by *user1*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] [-] Nothing to synchronize yet
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user1*] Finished with user *user1*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user2*] Running for user *user2*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user2*] [+] found system mail account in /home/*user2*/Maildir
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user2*] [+] found domain *domain4* owned by *user2*
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user2*] [+] found /home/*user2*/imap/*domain4*/*mailbox1*/Maildir
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user2*] [+] found /home/*user2*/imap/*domain4*/*mailbox2*/Maildir
    [Mon Oct  9 18:21:01 CEST 2017] [OK] [*user2*] [+] Found some emails under /home/*user2*/imap/*domain4*/*mailbox2*/Maildir/.INBOX.teach-isspam, now learning spam
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/SpamCop.pm:   lib/Mail/SpamAssassin/Plugin/SpamCop.pm: Permission denied at (eval 42) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/AutoLearnThreshold.pm:   lib/Mail/SpamAssassin/Plugin/AutoLearnThreshold.pm: Permission denied at (eval 43) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/WhiteListSubject.pm:   lib/Mail/SpamAssassin/Plugin/WhiteListSubject.pm: Permission denied at (eval 44) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/MIMEHeader.pm:   lib/Mail/SpamAssassin/Plugin/MIMEHeader.pm: Permission denied at (eval 45) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/ReplaceTags.pm:   lib/Mail/SpamAssassin/Plugin/ReplaceTags.pm: Permission denied at (eval 46) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/DKIM.pm:   lib/Mail/SpamAssassin/Plugin/DKIM.pm: Permission denied at (eval 47) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/Check.pm:   lib/Mail/SpamAssassin/Plugin/Check.pm: Permission denied at (eval 48) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/HTTPSMismatch.pm:   lib/Mail/SpamAssassin/Plugin/HTTPSMismatch.pm: Permission denied at (eval 49) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/URIDetail.pm:   lib/Mail/SpamAssassin/Plugin/URIDetail.pm: Permission denied at (eval 50) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/Bayes.pm:   lib/Mail/SpamAssassin/Plugin/Bayes.pm: Permission denied at (eval 51) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/BodyEval.pm:   lib/Mail/SpamAssassin/Plugin/BodyEval.pm: Permission denied at (eval 52) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/DNSEval.pm:   lib/Mail/SpamAssassin/Plugin/DNSEval.pm: Permission denied at (eval 53) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/HTMLEval.pm:   lib/Mail/SpamAssassin/Plugin/HTMLEval.pm: Permission denied at (eval 54) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/HeaderEval.pm:   lib/Mail/SpamAssassin/Plugin/HeaderEval.pm: Permission denied at (eval 55) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/MIMEEval.pm:   lib/Mail/SpamAssassin/Plugin/MIMEEval.pm: Permission denied at (eval 56) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/RelayEval.pm:   lib/Mail/SpamAssassin/Plugin/RelayEval.pm: Permission denied at (eval 57) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/URIEval.pm:   lib/Mail/SpamAssassin/Plugin/URIEval.pm: Permission denied at (eval 58) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/WLBLEval.pm:   lib/Mail/SpamAssassin/Plugin/WLBLEval.pm: Permission denied at (eval 59) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/VBounce.pm:   lib/Mail/SpamAssassin/Plugin/VBounce.pm: Permission denied at (eval 60) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/ImageInfo.pm:   lib/Mail/SpamAssassin/Plugin/ImageInfo.pm: Permission denied at (eval 61) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/FreeMail.pm:   lib/Mail/SpamAssassin/Plugin/FreeMail.pm: Permission denied at (eval 62) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/AskDNS.pm:   lib/Mail/SpamAssassin/Plugin/AskDNS.pm: Permission denied at (eval 63) line 1.
    ERROR: the Bayes learn function returned an error, please re-run with -D for more information at /usr/bin/sa-learn line 498.
    [Mon Oct  9 18:21:02 CEST 2017] [OK] [*user2*] [+] Teaching user SPAM from /home/*user2*/imap/*domain4*/*mailbox2*/Maildir/.INBOX.teach-isspam
    [Mon Oct  9 18:21:02 CEST 2017] [OK] [*user2*] [+] Learned tokens from 0 message(s) (1 message(s) examined)
    [Mon Oct  9 18:21:02 CEST 2017] [OK] [incognito] [-] No emails found under /home/*user2*/imap/*domain4*/*mailbox2*/Maildir/.INBOX.teach-isnotspam, skipping learning ham

    .... finding multiple mailboxes with the same errors .....
    
    [Mon Oct  9 18:21:07 CEST 2017] [OK] [*user2*] Finished with user *user2*

**Comment by poralix** [comment] 2017-10-09 19:42
Hello,

The "Can't locate" error is from SpamAssassin binary, it's not produced by a script. In order to fix it I'd suggest that you re-install SpamAssassin with custombuild in Directadmin:

```
cd /usr/local/directadmin/custombuild
./build update
./build spamassassin
```

if it does not help then you should check debug from:

```
sa-update -D
```

I'm closing the issue, as it's not caused by our script.

Regards,
Alex.

**Closed as completed by poralix** 2017-10-09 19:42 UTC

**Comment by jobhh** [comment] 2017-11-08 02:06
Suggested fix: Edit the script to set the current working directory to a directory that is readable by the user running sa-learn before running sa-learn.

This fixes sa-learn crashing if a user doesn't have rights on the current working directory for Perl versions below 5.26.0. The directory when running the script manually (_/usr/local/directadmin/scripts/custom/directadmin-teach-sa_) or when via a cronjob (_/etc/cron.d_) should not be readable by normal users. After this fix the default permissions of the scripts files and directory can also be set tighter.

----------------

Longer story:
It turns out I changed the permissions of the folder and files in my security review session, because I thought the default permissions of the script (drwxr-xr-x and -rwxr-xr-x) were quite loose when compared to other scripts (-rwx------). I think nobody apart from the owner (diradmin:diradmin) and root should have access to this folder and these files. Since root is running the script that shouldn't be a problem. The problem starts when running a Perl script as another user via sudo. 

I believe the issue is related to the users running sa-learn having no permissions on the current working directory (cwd). I think Perl tries to find the relevant .pm files in the cwd, the user running the Perl script (via sudo) doesn't have permissions on _/usr/local/directadmin/scripts/custom/directadmin-teach-sa_ and instead of searching the other locations in @INC Perl gives a hard error.

Reverting the permissions to the default (read and execute rights for everyone) made a manual run of the code finish without issues. It dit NOT fix the the cron.d job, so that is ran from a directory where the individual users don't have rights on.

I tested it as follows. Both commands were ran by the same user. The only difference is the directory the command was ran from.
Running from a user's home directory:

    mailuser@server:~$ /usr/bin/sa-learn --no-sync --spam ~/Maildir/.INBOX.teach-isspam/{cur,new}
    Learned tokens from 120 message(s) (363 message(s) examined)

When running from a directory this user does not have permission to (I went to /root as root and ran "su mailuser" before running the command):

    mailuser@server:/root$ /usr/bin/sa-learn --no-sync --spam ~/Maildir/INBOX.teach-isspam/{cur,new}
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/SpamCop.pm:   lib/Mail/SpamAssassin/Plugin/SpamCop.pm: Permission denied at (eval 42) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/AutoLearnThreshold.pm:   lib/Mail/SpamAssassin/Plugin/AutoLearnThreshold.pm: Permission denied at (eval 43) line 1.
    plugin: failed to parse plugin (from @INC): Can't locate Mail/SpamAssassin/Plugin/WhiteListSubject.pm:   lib/Mail/SpamAssassin/Plugin/WhiteListSubject.pm: Permission denied at (eval 44) line 1.
    *A lot more Permission denied messages*....

I think setting the cwd to a directory that is readable, such as / or the user's home directory, before running sa-learn as the user will fix the issue in the script and still allow for stricter permissions. I think this solution is preferable over making the folder readable and executable for everyone, for the script folder itself, but especially for the cron.d folder.

This resource helped me a lot: https://bugzilla.redhat.com/show_bug.cgi?id=1008415#c17

> sa-learn will fail if cwd is not readable. When started using su (and not su -) then it will keep the cwd which is likely to be /root, and it cannot read /root as that is not world readable and gives permission denied for non-root users.
> 
> ...
> 
> Ideally sa-learn would work properly even if . is not readable, or would at the very least give some useful error message.

**Sidenote**
I assume this issue is non-existent starting from Perl 5.26.0. The current working directory . was included in @INC until it was removed in Perl 5.26.0. However, Debian 9 still uses Perl 5.24.1. So the cwd is still included on my servers.

**Comment by poralix** [comment] 2017-11-12 08:42
Thank you for your details. Please try it now and let me know if the issues still persists.

**Comment by jobhh** [comment] 2017-11-13 11:40
The cron.d job now shows the same behaviour as when running the script manually 👍

**Comment by trueshanti** [comment] 2018-10-21 11:38
fyi: had the same issue , but was  my fault .. starting sa-learn from a wrong CWD
